In [1]:
# Import libraries and dependencies
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from iexfinance.stocks import get_historical_data
from iexfinance.refdata import get_symbols
from pathlib import Path
import requests
import os

In [2]:
iex_token = os.getenv("IEX_TOKEN")
type(iex_token)

str

### Define function to loop through tickers and their dates

In [3]:
def ticker_loop(ticker, date):
    '''
    Function that takes ticker and date of acquisition
    as argument to then pull data from all tickers from
    the year leading up to the acquisition. Lastly,
    it saves it to a CSV file.
    '''
    
    # Set start and end datetimes of 1 year of trading,
    # between date of acquisition and 252 days prior.
    end_date = date
    start_date = end_date + timedelta(-252)

    # Get 1 year's worth of historical data for ticker
    ticker_df = get_historical_data(
        ticker,
        start_date,
        end_date,
        token="pk_22cee6e066ef4f1c8a3b762936ab920f",
        output_format='pandas'
    )
    
    ticker_df.to_csv(f"{ticker}.csv")

In [4]:
acquisition_filepath = Path("/Users/robertocantu/rice_fintech_program/project_02/acquisition_dates.csv")

acquisition_data = pd.read_csv(
                        acquisition_filepath,
                        parse_dates=[6],
                        infer_datetime_format=True
                        )
acquisition_df = pd.DataFrame(acquisition_data)
acquisition_df = acquisition_df.iloc[:,:8].dropna()
acquisition_df

,Rank,Year,Acquirer Name,Target Name,Value (in bil. USD),Value (in bil. EUR),Date of Acquisition,Ticker
0,1.0,2000.0,America Online Inc,Time Warner,"16,474,686","16,071,303",2000-01-10,TWC
1,2.0,2013.0,Verizon Communications Inc,Verizon Wireless Inc,"13,029,832","10,046,001",2013-09-01,VZ
2,3.0,2000.0,Pfizer Inc,Warner-Lambert Co,"89,555,351","85,307,024",2000-02-07,WLA
3,4.0,2019.0,United Technologies Corp,Raytheon Co,"86,831,159","76,631,537",2019-06-09,RTN
4,5.0,2019.0,Walt Disney Co,21st Century Fox Inc,"84,197,032","72,502,064",2019-03-20,FOX
5,6.0,2018.0,AT&T Inc,Time Warner Inc,"7,940,646","72,942,774",2018-06-14,TWX
6,7.0,2019.0,Bristol-Myers Squibb Co,Celgene Corp,"79,376,825","69,677,691",2019-01-03,CELG
7,9.0,2006.0,AT&T Inc,BellSouth Corp,"72,670,997","60,178,126",2006-12-29,BLS
8,10.0,1998.0,Travelers Group Inc,Citicorp,"7,255,818","6,724,576",1998-04-06,C
9,11.0,2002.0,Comcast Corp,AT&T Broadband & Internet Svcs,"7,204,115","85,094,646",2002-11-18,T
10,12.0,2018.0,Cigna Corp,Express Scripts Holding Co,"6,977,018","5,621,188",2018-12-20,ESRX
11,13.0,2018.0,Actavis PLC,Allergan Inc,"68,445,401","49,616,071",2018-03-17,AGN
12,14.0,2018.0,CVS Health Corp,Aetna Inc,"67,822,818","58,185,196",2018-11-28,AET
13,15.0,2009.0,Pfizer Inc,Wyeth,"67,285,695","51,877,271",2009-10-15,WYE
14,16.0,2015.0,Dell Inc,EMC Corp,"65,999,778","51,380,827",2015-10-12,EMC
15,17.0,1999.0,SBC Communications Inc,Ameritech Corp,"62,592,542","56,481,257",1999-10-08,AMTR
16,18.0,2015.0,The Dow Chemical Co,DuPont,"62,141,056","5,638,058",2017-08-31,DD
17,19.0,2019.0,AbbVie Inc,Allergan PLC,"62,117,141","546,565",2019-06-25,AGN
18,20.0,1998.0,NationsBank Corp,BankAmerica Corp,"61,633,402","56,674,378",1998-09-30,BAC
19,21.0,1999.0,Vodafone Group PLC,AirTouch Communications Inc,"60,286,874","5,165,084",1999-06-29,ATCH
20,23.0,2003.0,Pfizer Inc,Pharmacia Corp,"59,515,024","60,019,176",2003-04-16,PHABF
21,25.0,2004.0,JPMorgan Chase & Co,Bank One Corp,"58,663,146","4,593,911",2004-07-01,ONE
22,26.0,2016.0,Bayer AG,Monsanto Co,"56,598,044","49,749,681",2018-06-07,MON
23,27.0,2000.0,Qwest Commun Intl Inc,US WEST Inc,"56,307,028","52,796,116",2000-06-30,USW
24,28.0,2015.0,Charter Communications Inc,Time Warner Cable Inc,"55,637,581","51,125,373",2015-05-16,TWC
25,32.0,1998.0,AT&T Corp,Tele-Communications Inc,"53,592,491","4,878,696",1998-06-24,TCI
26,33.0,1998.0,Bell Atlantic Corp,GTE Corp,"53,414,579","48,199,393",1998-07-28,GTE
27,34.0,2008.0,InBev NV,Anheuser-Busch Cos Inc,"52,177,662","39,727,028",2008-07-13,BUD
28,36.0,2005.0,AT&T Corp,MediaOne Group Inc,"49,278,866","4,530,556",2005-11-18,UMG
29,37.0,2004.0,Bank of America Corp,"FleetBoston Financial Corp,MA","49,260,627","41,803,061",2004-04-01,FBF
30,39.0,2017.0,British American Tobacco PLC,Reynolds American Inc,"49,053,658","4,506,069",2017-07-25,RAI
31,40.0,2009.0,Bank of America Corp,Merrill Lynch & Co Inc,"48,766,153","34,063,158",2009-01-01,MER
32,41.0,1998.0,British Petroleum Co PLC,Amoco Corp,"48,174,085","43,529,477",1998-08-11,AMOCO
33,42.0,2015.0,AT&T Inc,DirecTV Inc,"48,082,294","34,667,334",2015-07-24,DTV
34,43.0,2009.0,Roche Holdings AG,Genentech Inc,"46,694,838","29,319,689",2009-03-25,GENE
35,44.0,2015.0,Hj Heinz Co,Kraft Foods Group Inc,"46,105,535","42,218,838",2015-07-02,MDLZ
36,45.0,2000.0,Chevron Corp,Texaco Inc,"428,723","5,040,835",2000-10-15,TX
37,46.0,2015.0,Medtronic Inc,Covidien PLC,"42,729,867","31,560,275",2015-01-26,COV
38,49.0,2000.0,JDS Uniphase Corp,SDL Inc,"41,143,566","41,647,492",2000-07-11,SDL
39,50.0,2004.0,JDS Uniphase Corp,AT&T Wireless Services Inc,"41,005,408","32,111,335",2004-10-26,T

### For loop for tickers and their dates from DataFrame

In [9]:
ticker_list = ["RTN","FOX","CELG","AGN","DD","DTV","MDLZ"]

In [6]:
for ticker, date in zip(acquisition_df["Ticker"], acquisition_df["Date of Acquisition"]):
    
    try:
        ticker_loop(ticker, date)
        ticker_list.append(ticker)
        print(f"{ticker} has been saved as DataFrame.")
        
    except:
        print(f"{ticker} has no data.")

TWC has no data.
VZ has no data.
WLA has no data.
RTN has been saved as DataFrame.
FOX has been saved as DataFrame.
TWX has no data.
CELG has been saved as DataFrame.
BLS has no data.
C has no data.
T has no data.
ESRX has no data.
AGN has been saved as DataFrame.
AET has no data.
WYE has no data.
EMC has no data.
AMTR has no data.
DD has been saved as DataFrame.
AGN has been saved as DataFrame.
BAC has no data.
ATCH has no data.
PHABF has no data.
ONE has no data.
MON has no data.
USW has no data.
TWC has no data.
TCI has no data.
GTE has no data.
BUD has no data.
UMG has no data.
FBF has no data.
RAI has no data.
MER has no data.
AMOCO has no data.
DTV has been saved as DataFrame.
GENE has no data.
MDLZ has been saved as DataFrame.
TX has no data.
COV has no data.
SDL has no data.
T has no data.

In [10]:
ticker_list

['RTN', 'FOX', 'CELG', 'AGN', 'DD', 'DTV', 'MDLZ']

In [11]:
def ticker_pct_change(df):
    '''
    Function that takes in ticker
    CSV files and calculates pct_change
    of the "close" column.
    '''
    
    df["pct_change"] = df["close"].pct_change()

In [20]:
main_df = pd.DataFrame(index=ticker_list)

In [27]:
for ticker in ticker_list:
    
    try:
        filepath = Path(f"{ticker}.csv")

        ticker_data = pd.read_csv(filepath)

        ticker_df = pd.DataFrame(ticker_data)

        ticker_pct_change(ticker_df)
        
        ticker_df = ticker_df.drop(columns = ["date","open","high","low","close","volume"])
        
        print(ticker, ticker_df.head())

        # main_df.loc[f"ticker"] = ticker_df["pct_change"]
        
    except:
        print(f"Encountered error with {ticker}.")

RTN    pct_change
0         NaN
1    0.002554
2   -0.005143
3    0.005991
4   -0.007012
FOX    pct_change
0         NaN
1    0.019388
2    0.026527
3   -0.003901
4   -0.032061
CELG    pct_change
0         NaN
1   -0.009774
2   -0.044747
3    0.009529
4   -0.011714
AGN    pct_change
0         NaN
1    0.016011
2   -0.011047
3    0.003388
4   -0.009972
DD    pct_change
0         NaN
1   -0.005447
2   -0.000171
3   -0.008901
4   -0.008290
Encountered error with DTV.
MDLZ    pct_change
0         NaN
1    0.008600
2    0.010336
3   -0.004348
4    0.001798

In [23]:
main_df

Empty DataFrame
Columns: []
Index: [RTN, FOX, CELG, AGN, DD, DTV, MDLZ]