In [1]:
# Import libraries and dependencies
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from iexfinance.stocks import get_historical_data
from iexfinance.refdata import get_symbols
from pathlib import Path
import requests
import os

In [2]:
iex_token = os.getenv("IEX_TOKEN")
type(iex_token)

str

### Define function to loop through tickers and their dates

In [3]:
def ticker_loop(ticker, date):
    '''
    Function that takes ticker and date of acquisition
    as argument to then pull data from all tickers from
    the year leading up to the acquisition. Lastly,
    it saves it to a CSV file.
    '''
    
    # Set start and end datetimes of 1 year of trading,
    # between date of acquisition and 365 days prior.
    end_date = date
    start_date = end_date + timedelta(-365)

    # Get 1 year's worth of historical data for ticker
    ticker_df = get_historical_data(
        ticker,
        start_date,
        end_date,
        token="pk_22cee6e066ef4f1c8a3b762936ab920f",
        output_format='pandas'
    )
    
    # Save ticker infor as CSV
    ticker_df.to_csv(f"{ticker}.csv")

In [3]:
# Create Path for needed CSV file
acquisition_filepath = Path("/Users/robertocantu/rice_fintech_program/project_02/acquisition_dates.csv")

# Read the necessary CSV file
acquisition_data = pd.read_csv(
                        acquisition_filepath,
                        parse_dates=[6],
                        infer_datetime_format=True
                        )

# Create DataFrame for CSV file
acquisition_df = pd.DataFrame(acquisition_data)

# Only keep the first 8 columns, and drop empty rows
acquisition_df = acquisition_df.iloc[:,:8].dropna()

acquisition_df

,Rank,Year,Acquirer Name,Target Name,Value (in bil. USD),Value (in bil. EUR),Date of Acquisition,Ticker
0,1.0,2000.0,America Online Inc,Time Warner,"16,474,686","16,071,303",2000-01-10,TWC
1,2.0,2013.0,Verizon Communications Inc,Verizon Wireless Inc,"13,029,832","10,046,001",2013-09-01,VZ
2,3.0,2000.0,Pfizer Inc,Warner-Lambert Co,"89,555,351","85,307,024",2000-02-07,WLA
3,4.0,2019.0,United Technologies Corp,Raytheon Co,"86,831,159","76,631,537",2019-06-09,RTN
4,5.0,2019.0,Walt Disney Co,21st Century Fox Inc,"84,197,032","72,502,064",2019-03-20,FOX
5,6.0,2018.0,AT&T Inc,Time Warner Inc,"7,940,646","72,942,774",2018-06-14,TWX
6,7.0,2019.0,Bristol-Myers Squibb Co,Celgene Corp,"79,376,825","69,677,691",2019-01-03,CELG
7,9.0,2006.0,AT&T Inc,BellSouth Corp,"72,670,997","60,178,126",2006-12-29,BLS
8,10.0,1998.0,Travelers Group Inc,Citicorp,"7,255,818","6,724,576",1998-04-06,C
9,11.0,2002.0,Comcast Corp,AT&T Broadband & Internet Svcs,"7,204,115","85,094,646",2002-11-18,T
10,12.0,2018.0,Cigna Corp,Express Scripts Holding Co,"6,977,018","5,621,188",2018-12-20,ESRX
11,13.0,2018.0,Actavis PLC,Allergan Inc,"68,445,401","49,616,071",2018-03-17,AGN
12,14.0,2018.0,CVS Health Corp,Aetna Inc,"67,822,818","58,185,196",2018-11-28,AET
13,15.0,2009.0,Pfizer Inc,Wyeth,"67,285,695","51,877,271",2009-10-15,WYE
14,16.0,2015.0,Dell Inc,EMC Corp,"65,999,778","51,380,827",2015-10-12,EMC
15,17.0,1999.0,SBC Communications Inc,Ameritech Corp,"62,592,542","56,481,257",1999-10-08,AMTR
16,18.0,2015.0,The Dow Chemical Co,DuPont,"62,141,056","5,638,058",2017-08-31,DD
17,19.0,2019.0,AbbVie Inc,Allergan PLC,"62,117,141","546,565",2019-06-25,AGN
18,20.0,1998.0,NationsBank Corp,BankAmerica Corp,"61,633,402","56,674,378",1998-09-30,BAC
19,21.0,1999.0,Vodafone Group PLC,AirTouch Communications Inc,"60,286,874","5,165,084",1999-06-29,ATCH
20,23.0,2003.0,Pfizer Inc,Pharmacia Corp,"59,515,024","60,019,176",2003-04-16,PHABF
21,25.0,2004.0,JPMorgan Chase & Co,Bank One Corp,"58,663,146","4,593,911",2004-07-01,ONE
22,26.0,2016.0,Bayer AG,Monsanto Co,"56,598,044","49,749,681",2018-06-07,MON
23,27.0,2000.0,Qwest Commun Intl Inc,US WEST Inc,"56,307,028","52,796,116",2000-06-30,USW
24,28.0,2015.0,Charter Communications Inc,Time Warner Cable Inc,"55,637,581","51,125,373",2015-05-16,TWC
25,32.0,1998.0,AT&T Corp,Tele-Communications Inc,"53,592,491","4,878,696",1998-06-24,TCI
26,33.0,1998.0,Bell Atlantic Corp,GTE Corp,"53,414,579","48,199,393",1998-07-28,GTE
27,34.0,2008.0,InBev NV,Anheuser-Busch Cos Inc,"52,177,662","39,727,028",2008-07-13,BUD
28,36.0,2005.0,AT&T Corp,MediaOne Group Inc,"49,278,866","4,530,556",2005-11-18,UMG
29,37.0,2004.0,Bank of America Corp,"FleetBoston Financial Corp,MA","49,260,627","41,803,061",2004-04-01,FBF
30,39.0,2017.0,British American Tobacco PLC,Reynolds American Inc,"49,053,658","4,506,069",2017-07-25,RAI
31,40.0,2009.0,Bank of America Corp,Merrill Lynch & Co Inc,"48,766,153","34,063,158",2009-01-01,MER
32,41.0,1998.0,British Petroleum Co PLC,Amoco Corp,"48,174,085","43,529,477",1998-08-11,AMOCO
33,42.0,2015.0,AT&T Inc,DirecTV Inc,"48,082,294","34,667,334",2015-07-24,DTV
34,43.0,2009.0,Roche Holdings AG,Genentech Inc,"46,694,838","29,319,689",2009-03-25,GENE
35,44.0,2015.0,Hj Heinz Co,Kraft Foods Group Inc,"46,105,535","42,218,838",2015-07-02,MDLZ
36,45.0,2000.0,Chevron Corp,Texaco Inc,"428,723","5,040,835",2000-10-15,TX
37,46.0,2015.0,Medtronic Inc,Covidien PLC,"42,729,867","31,560,275",2015-01-26,COV
38,49.0,2000.0,JDS Uniphase Corp,SDL Inc,"41,143,566","41,647,492",2000-07-11,SDL
39,50.0,2004.0,JDS Uniphase Corp,AT&T Wireless Services Inc,"41,005,408","32,111,335",2004-10-26,T

### For loop for tickers and their dates from DataFrame

In [4]:
# Create list of tickers
ticker_list = ["RTN","FOX","CELG","AGN","DD","DTV","MDLZ"]

In [5]:
'''
# For loop to iterate through both tickers and date and create indivdual CSVs
for ticker, date in zip(acquisition_df["Ticker"], acquisition_df["Date of Acquisition"]):
    
    try:
        # Call the function to get data for tickers
        ticker_loop(ticker, date)
        
        # Add ticker to list of tickers
        ticker_list.append(ticker)
        
        print(f"{ticker} has been saved as DataFrame.")
        
    except:
        # Print statement if data cannot be accessed
        print(f"{ticker} has no data.")
'''

'\n# For loop to iterate through both tickers and date and create indivdual CSVs\nfor ticker, date in zip(acquisition_df["Ticker"], acquisition_df["Date of Acquisition"]):\n    \n    try:\n        # Call the function to get data for tickers\n        ticker_loop(ticker, date)\n        \n        # Add ticker to list of tickers\n        ticker_list.append(ticker)\n        \n        print(f"{ticker} has been saved as DataFrame.")\n        \n    except:\n        # Print statement if data cannot be accessed\n        print(f"{ticker} has no data.")\n'

In [6]:
ticker_list

['RTN', 'FOX', 'CELG', 'AGN', 'DD', 'DTV', 'MDLZ']

In [7]:
def ticker_pct_change(df):
    '''
    Function that takes in ticker
    CSV files and calculates pct_change
    of the "close" column.
    '''
    
    df["pct_change"] = df["close"].pct_change()

In [9]:
# Iterate through list of tickers to create new CSVs
# with needed PCT Change value as new column
for ticker in ticker_list:
    
    try:
        # Bring in the previously created CSV files
        filepath = Path(f"{ticker}.csv")
        
        # Read the CSV
        ticker_data = pd.read_csv(filepath)
        
        # Create new DataFrame from CSV
        ticker_df = pd.DataFrame(ticker_data)
        
        # Apply pct_change function to close value
        ticker_pct_change(ticker_df)
        
        # Drop unnecessary columns
        ticker_df = ticker_df.drop(columns = ["date","open","high","low","close","volume"])
        
        # Save new CSV as its own file
        ticker_df.to_csv(f"{ticker}_pct_change.csv")
        
        print(ticker, ticker_df.head())

        # main_df.loc[f"ticker"] = ticker_df["pct_change"]
        
    except:
        print(f"Encountered error with {ticker}.")

RTN    pct_change
0         NaN
1    0.002554
2   -0.005143
3    0.005991
4   -0.007012
FOX    pct_change
0         NaN
1    0.019388
2    0.026527
3   -0.003901
4   -0.032061
CELG    pct_change
0         NaN
1   -0.009774
2   -0.044747
3    0.009529
4   -0.011714
AGN    pct_change
0         NaN
1    0.016011
2   -0.011047
3    0.003388
4   -0.009972
DD    pct_change
0         NaN
1   -0.005447
2   -0.000171
3   -0.008901
4   -0.008290
Encountered error with DTV.
MDLZ    pct_change
0         NaN
1    0.008600
2    0.010336
3   -0.004348
4    0.001798

In [10]:
ticker_dfs = []

In [11]:
# Iterate through list of tickers to concat
# all pct_change CSVs to one main_df
for ticker in ticker_list:
    
    try:
        # Bring in the previously created CSV files
        filepath = Path(f"{ticker}_pct_change.csv")
        
        # Read the CSV
        ticker_data = pd.read_csv(filepath, index_col=0)
        
        # Create new DataFrame from CSV
        ticker_df = pd.DataFrame(ticker_data)
        
        # Create new DataFrame from CSV
        ticker_df[f"{ticker}"] = ticker_df["pct_change"]
        
        ticker_df = ticker_df.drop(columns="pct_change")
        
        # Add name of df to ticker_dfs list
        ticker_dfs.append(ticker_df)
        
    except:
        print(f"Encountered error with {ticker}.")

Encountered error with DTV.

In [12]:
ticker_dfs

[          RTN
 0         NaN
 1    0.002554
 2   -0.005143
 3    0.005991
 4   -0.007012
 5    0.000339
 6   -0.010782
 7   -0.034166
 8   -0.033451
 9    0.003665
 10   0.002974
 11   0.019037
 12  -0.014292
 13  -0.007560
 14  -0.003391
 15   0.000471
 16   0.001465
 17  -0.048438
 18  -0.030696
 19   0.002096
 20  -0.048279
 21   0.028453
 22   0.010974
 23   0.033078
 24   0.003982
 25   0.008317
 26   0.009505
 27   0.013636
 28  -0.003523
 29   0.007286
 ..        ...
 142  0.000338
 143 -0.011272
 144  0.012313
 145 -0.007039
 146  0.003970
 147  0.012765
 148  0.007306
 149 -0.011849
 150  0.002577
 151  0.005924
 152  0.001389
 153 -0.009099
 154 -0.004031
 155 -0.003373
 156  0.012184
 157 -0.013208
 158  0.020331
 159  0.010849
 160 -0.011499
 161 -0.004542
 162  0.001614
 163 -0.008056
 164 -0.005601
 165 -0.006252
 166 -0.010995
 167  0.009742
 168  0.016232
 169  0.018262
 170  0.007075
 171  0.012471

 [172 rows x 1 columns],         FOX
 0       NaN
 1  0.019388
 2  0.026527
 3 -0.003901
 4 -0.032061
 5 -0.049305,          CELG
 0         NaN
 1   -0.009774
 2   -0.044747
 3    0.009529
 4   -0.011714
 5   -0.017261
 6    0.017447
 7   -0.026700
 8   -0.017027
 9   -0.003970
 10  -0.005072
 11   0.026220
 12   0.009108
 13  -0.039034
 14  -0.007563
 15  -0.016962
 16  -0.020130
 17  -0.046957
 18   0.025706
 19   0.013706
 20   0.024208
 21  -0.011441
 22  -0.010174
 23   0.001799
 24   0.009106
 25   0.004575
 26  -0.004934
 27  -0.008646
 28   0.010517
 29   0.000000
 ..        ...
 144 -0.003589
 145 -0.038184
 146  0.011835
 147 -0.013177
 148  0.020255
 149  0.017500
 150  0.025871
 151 -0.011553
 152  0.029361
 153  0.016616
 154 -0.012939
 155  0.004554
 156 -0.037363
 157 -0.019977
 158  0.011794
 159  0.020291
 160 -0.016361
 161 -0.022082
 162 -0.001026
 163 -0.022017
 164 -0.015759
 165 -0.016163
 166 -0.055797
 167 -0.028070
 168  0.055565
 169  0.004960
 170 -0.006050
 171  0.026590
 172  0.039788
 173  0.206933

 [174 rows x 1 columns],           AGN
 0         NaN
 1    0.016011
 2   -0.011047
 3    0.003388
 4   -0.009972
 5    0.000053
 6   -0.046576
 7    0.007713
 8   -0.017139
 9   -0.019187
 10  -0.075547
 11  -0.016556
 12   0.040820
 13  -0.008574
 14   0.014842
 15  -0.001571
 16   0.026633
 17  -0.001769
 18  -0.022385
 19  -0.009969
 20  -0.007445
 21  -0.030310
 22   0.010462
 23  -0.012424
 24  -0.008577
 25  -0.016919
 26   0.006063
 27  -0.004665
 28  -0.002929
 29  -0.007378
 ..        ...
 143  0.007037
 144  0.005516
 145  0.024358
 146  0.001143
 147 -0.010128
 148 -0.002162
 149  0.007438
 150 -0.010537
 151 -0.018328
 152 -0.030256
 153 -0.043680
 154 -0.025861
 155 -0.004166
 156  0.010007
 157  0.044506
 158 -0.016406
 159 -0.011462
 160  0.016633
 161 -0.004090
 162 -0.029697
 163 -0.004721
 164 -0.010387
 165 -0.041983
 166 -0.001639
 167  0.042426
 168  0.062334
 169  0.020755
 170 -0.000076
 171 -0.009479
 172  0.253608

 [173 rows x 1 columns],            DD
 0         NaN
 1   -0.005447
 2   -0.000171
 3   -0.008901
 4   -0.008290
 5   -0.003483
 6    0.006641
 7    0.007986
 8   -0.004478
 9   -0.006228
 10   0.006093
 11  -0.002076
 12   0.010231
 13   0.000515
 14  -0.008406
 15  -0.008131
 16   0.006628
 17  -0.010743
 18   0.005080
 19  -0.004183
 20   0.043752
 21   0.009557
 22   0.020096
 23  -0.001791
 24  -0.018920
 25  -0.008645
 26   0.011236
 27  -0.007297
 28   0.005847
 29  -0.003156
 ..        ...
 144 -0.003766
 145  0.001210
 146  0.009514
 147 -0.006432
 148 -0.004818
 149 -0.006354
 150 -0.021924
 151  0.007005
 152 -0.006029
 153 -0.013530
 154  0.010720
 155 -0.003588
 156 -0.007358
 157  0.001419
 158 -0.006142
 159  0.002377
 160  0.002371
 161  0.004100
 162  0.004241
 163 -0.011886
 164  0.003482
 165  0.007256
 166  0.014407
 167 -0.003087
 168 -0.003561
 169  0.002953
 170  0.002014
 171 -0.006958
 172  0.010589
 173  0.026965

 [174 rows x 1 columns],          MDLZ
 0         NaN
 1    0.008600
 2    0.010336
 3   -0.004348
 4    0.001798
 5   -0.000256
 6   -0.005899
 7    0.006192
 8    0.005128
 9   -0.005612
 10  -0.002309
 11  -0.005657
 12  -0.006724
 13   0.002343
 14  -0.006753
 15   0.008368
 16  -0.011670
 17   0.000525
 18  -0.023603
 19  -0.015042
 20  -0.017726
 21  -0.000555
 22   0.016111
 23   0.019683
 24   0.005362
 25   0.002133
 26   0.001330
 27   0.003455
 28  -0.011123
 29  -0.008570
 ..        ...
 127 -0.008608
 128 -0.003473
 129 -0.005726
 130  0.005008
 131  0.008221
 132  0.027675
 133 -0.021640
 134  0.002703
 135  0.005637
 136 -0.014867
 137 -0.009896
 138  0.000750
 139  0.004245
 140  0.003729
 141 -0.000248
 142  0.002725
 143 -0.008895
 144  0.015707
 145  0.001227
 146  0.001471
 147  0.004651
 148  0.000244
 149  0.001218
 150 -0.000487
 151  0.000000
 152  0.000730
 153 -0.006568
 154  0.007346
 155  0.011424
 156 -0.001442

 [157 rows x 1 columns]]

In [33]:
main_acq_df = pd.concat(ticker_dfs, axis=1)

main_acq_df = main_acq_df.transpose()

for index in main_acq_df.iterrows():
    
    main_acq_df["acquired"] = 1

main_acq_df.head()

,0,1,2,3,4,5,6,7,8,9,...,165,166,167,168,169,170,171,172,173,acquired
RTN,NaN,0.002554,-0.005143,0.005991,-0.007012,0.000339,-0.010782,-0.034166,-0.033451,0.003665,...,-0.006252,-0.010995,0.009742,0.016232,0.018262,0.007075,0.012471,NaN,NaN,1
FOX,NaN,0.019388,0.026527,-0.003901,-0.032061,-0.049305,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
CELG,NaN,-0.009774,-0.044747,0.009529,-0.011714,-0.017261,0.017447,-0.026700,-0.017027,-0.003970,...,-0.016163,-0.055797,-0.028070,0.055565,0.004960,-0.006050,0.026590,0.039788,0.206933,1
AGN,NaN,0.016011,-0.011047,0.003388,-0.009972,0.000053,-0.046576,0.007713,-0.017139,-0.019187,...,-0.041983,-0.001639,0.042426,0.062334,0.020755,-0.000076,-0.009479,0.253608,NaN,1
DD,NaN,-0.005447,-0.000171,-0.008901,-0.008290,-0.003483,0.006641,0.007986,-0.004478,-0.006228,...,0.007256,0.014407,-0.003087,-0.003561,0.002953,0.002014,-0.006958,0.010589,0.026965,1

# Process for cleaning data of non-acquired companies

In [18]:
def nonacq_ticker_loop(ticker):
    '''
    Function that takes ticker and date of acquisition
    as argument to then pull data from all tickers from
    the year leading up to the acquisition. Lastly,
    it saves it to a CSV file.
    '''
    
    # Set start and end datetimes of 1 year of trading,
    # between date of acquisition and 252 days prior.
    end_date = datetime.now()
    start_date = end_date + timedelta(-252)

    # Get 1 year's worth of historical data for ticker
    ticker_df = get_historical_data(
        ticker,
        start_date,
        end_date,
        token="pk_22cee6e066ef4f1c8a3b762936ab920f",
        output_format='pandas'
    )
    
    # Save ticker infor as CSV
    ticker_df.to_csv(f"nonacq_{ticker}.csv")

In [15]:
# Create Path for needed CSV file
non_acquisition_filepath = Path("/Users/robertocantu/rice_fintech_program/project_02/cleanedcompanylist.csv")

# Read the necessary CSV file
non_acquisition_data = pd.read_csv(
                        non_acquisition_filepath,
                        infer_datetime_format=True
                        )

# Create DataFrame for CSV file
non_acquisition_df = pd.DataFrame(non_acquisition_data)

non_acquisition_df

,Symbol,Name,LastSale,MarketCap,IPOyear,Sector,industry
0,ACM,AECOM,43.19,$6.81B,2007.0,Consumer Services,Military/Government/Technical
1,AA,Alcoa Corporation,20.89,$3.88B,2016.0,Basic Industries,Aluminum
2,APLE,"Apple Hospitality REIT, Inc.",16.08,$3.6B,2015.0,Consumer Services,Real Estate Investment Trusts
3,BCS,Barclays PLC,8.78,$37.91B,NaN,Finance,Commercial Banks
4,BRK.B,Berkshire Hathaway Inc.,NaN,NaN,NaN,NaN,NaN
5,BHP,BHP Group Limited,50.89,$128.7B,NaN,Basic Industries,Precious Metals
6,BLK,"BlackRock, Inc.",490.96,$76.19B,1999.0,Finance,Investment Bankers/Brokers/Service
7,BA,Boeing Company (The),371.68,$209.18B,NaN,Capital Goods,Aerospace
8,BP,BP p.l.c.,39.21,$132.82B,NaN,Energy,Integrated oil Companies
9,CAT,"Caterpillar, Inc.",145.31,$80.31B,NaN,Capital Goods,Construction/Ag Equipment/Trucks
10,CBRE,"CBRE Group, Inc.",56.44,$18.89B,NaN,Finance,Real Estate
11,CHGG,"Chegg, Inc.",36.57,$4.38B,2013.0,Consumer Services,Other Consumer Services
12,CHWY,"Chewy, Inc.",23.40,$9.33B,2019.0,Consumer Services,Catalog/Specialty Distribution
13,KO,Coca-Cola Company (The),52.67,$225.66B,NaN,Consumer Non-Durables,Beverages (Production/Distribution)
14,RACE,Ferrari N.V.,167.00,$41.62B,2015.0,Capital Goods,Auto Manufacturing
15,F,Ford Motor Company,8.95,$35.49B,NaN,Capital Goods,Auto Manufacturing
16,GM,General Motors Company,36.89,$53.55B,2010.0,Capital Goods,Auto Manufacturing
17,GS,"Goldman Sachs Group, Inc. (The)",220.25,$77.99B,1999.0,Finance,Investment Bankers/Brokers/Service
18,HAL,Halliburton Company,20.48,$17.98B,NaN,Energy,Oilfield Services/Equipment
19,IBM,International Business Machines Corporation,134.40,$119.03B,NaN,Technology,Computer Manufacturing
20,LAZ,Lazard Ltd.,37.80,$3.97B,2005.0,Finance,Investment Managers
21,LEVI,Levi Strauss & Co,17.18,$6.75B,2019.0,Consumer Non-Durables,Apparel
22,MC,Moelis & Company,33.72,$1.66B,2014.0,Finance,Investment Managers
23,MS,Morgan Stanley,48.99,$79.3B,NaN,Finance,Investment Bankers/Brokers/Service
24,JWN,"Nordstrom, Inc.",38.04,$5.91B,NaN,Consumer Services,Clothing/Shoe/Accessory Stores
25,ORCL,Oracle Corporation,56.42,$185.2B,1986.0,Technology,Computer Software: Prepackaged Software
26,PCG,Pacific Gas & Electric Co.,7.42,$3.93B,NaN,Public Utilities,Power Generation
27,PFE,"Pfizer, Inc.",37.28,$206.31B,NaN,Health Care,Major Pharmaceuticals
28,RL,Ralph Lauren Corporation,112.61,$8.4B,1997.0,Consumer Non-Durables,Apparel
29,CRM,Salesforce.com Inc,163.21,$143.14B,2004.0,Technology,Computer Software: Prepackaged Software
30,SLB,Schlumberger N.V.,35.36,$48.95B,NaN,Energy,Oilfield Services/Equipment
31,SHAK,"Shake Shack, Inc.",62.66,$2.35B,2015.0,Consumer Services,Restaurants
32,SHW,Sherwin-Williams Company (The),592.77,$54.72B,NaN,Consumer Services,RETAIL: Building Materials
33,SHOP,Shopify Inc.,312.38,$32.55B,2015.0,Technology,Computer Software: Prepackaged Software
34,SNAP,Snap Inc.,13.94,$19.52B,2017.0,Technology,"Computer Software: Programming, Data Processing"
35,SPOT,Spotify Technology S.A.,147.51,$25.75B,2018.0,Consumer Services,Broadcasting
36,BX,The Blackstone Group Inc.,52.52,$62.99B,2007.0,Finance,Investment Managers
37,TIF,Tiffany & Co.,125.08,$15.11B,1987.0,Consumer Services,Consumer Specialties
38,UBER,"Uber Technologies, Inc.",26.79,$45.7B,2019.0,Miscellaneous,Business Services
39,V,Visa Inc.,179.77,$401.14B,NaN,Miscellaneous,Business Services
40,WMT,Walmart Inc.,118.87,$338.1B,NaN,Consumer Services,Department/Specialty Retail Stores
41,WM,"Waste Management, Inc.",112.16,$47.58B,NaN,Public Utilities,Environmental Services

In [19]:
# Create list of tickers
nonacq_ticker_list = []

In [20]:
# For loop to iterate through both tickers and date and create indivdual CSVs
for ticker in non_acquisition_df["Symbol"]:
    
    try:
        # Call the function to get data for tickers
        nonacq_ticker_loop(ticker)
        
        # Add ticker to list of tickers
        nonacq_ticker_list.append(ticker)
        
        print(f"{ticker} has been saved as DataFrame.")
        
    except:
        # Print statement if data cannot be accessed
        print(f"{ticker} has no data.")

ACM has been saved as DataFrame.
AA has been saved as DataFrame.
APLE has been saved as DataFrame.
BCS has been saved as DataFrame.
BRK.B has been saved as DataFrame.
BHP has been saved as DataFrame.
BLK has been saved as DataFrame.
BA has been saved as DataFrame.
BP has been saved as DataFrame.
CAT has been saved as DataFrame.
CBRE has been saved as DataFrame.
CHGG has been saved as DataFrame.
CHWY has been saved as DataFrame.
KO has been saved as DataFrame.
RACE has been saved as DataFrame.
F has been saved as DataFrame.
GM has been saved as DataFrame.
GS has been saved as DataFrame.
HAL has been saved as DataFrame.
IBM has been saved as DataFrame.
LAZ has been saved as DataFrame.
LEVI has been saved as DataFrame.
MC has been saved as DataFrame.
MS has been saved as DataFrame.
JWN has been saved as DataFrame.
ORCL has been saved as DataFrame.
PCG has been saved as DataFrame.
PFE has been saved as DataFrame.
RL has been saved as DataFrame.
CRM has been saved as DataFrame.
SLB has been saved as DataFrame.
SHAK has been saved as DataFrame.
SHW has been saved as DataFrame.
SHOP has been saved as DataFrame.
SNAP has been saved as DataFrame.
SPOT has been saved as DataFrame.
BX has been saved as DataFrame.
TIF has been saved as DataFrame.
UBER has been saved as DataFrame.
V has been saved as DataFrame.
WMT has been saved as DataFrame.
WM has been saved as DataFrame.

In [21]:
nonacq_ticker_list

['ACM',
 'AA',
 'APLE',
 'BCS',
 'BRK.B',
 'BHP',
 'BLK',
 'BA',
 'BP',
 'CAT',
 'CBRE',
 'CHGG',
 'CHWY',
 'KO',
 'RACE',
 'F',
 'GM',
 'GS',
 'HAL',
 'IBM',
 'LAZ',
 'LEVI',
 'MC',
 'MS',
 'JWN',
 'ORCL',
 'PCG',
 'PFE',
 'RL',
 'CRM',
 'SLB',
 'SHAK',
 'SHW',
 'SHOP',
 'SNAP',
 'SPOT',
 'BX',
 'TIF',
 'UBER',
 'V',
 'WMT',
 'WM']

In [22]:
def nonacq_ticker_pct_change(df):
    '''
    Function that takes in ticker
    CSV files and calculates pct_change
    of the "close" column.
    '''
    
    df["pct_change"] = df["close"].pct_change()

In [23]:
# Iterate through list of tickers to create new CSVs
# with needed PCT Change value as new column
for ticker in nonacq_ticker_list:
    
    try:
        # Bring in the previously created CSV files
        filepath = Path(f"nonacq_{ticker}.csv")
        
        # Read the CSV
        ticker_data = pd.read_csv(filepath)
        
        # Create new DataFrame from CSV
        ticker_df = pd.DataFrame(ticker_data)
        
        # Apply pct_change function to close value
        nonacq_ticker_pct_change(ticker_df)
        
        # Drop unnecessary columns
        ticker_df = ticker_df.drop(columns = ["date","open","high","low","close","volume"])
        
        # Save new CSV as its own file
        ticker_df.to_csv(f"nonacq_{ticker}_pct_change.csv")
        
        print(ticker, ticker_df.head())

        # main_df.loc[f"ticker"] = ticker_df["pct_change"]
        
    except:
        print(f"Encountered error with {ticker}.")

ACM    pct_change
0         NaN
1   -0.002633
2    0.002970
3   -0.002303
4    0.000000
AA    pct_change
0         NaN
1    0.033430
2    0.018987
3   -0.037612
4   -0.001793
APLE    pct_change
0         NaN
1    0.001218
2    0.000000
3    0.002433
4   -0.001820
BCS    pct_change
0         NaN
1    0.009490
2    0.017626
3    0.004619
4    0.008046
BRK.B    pct_change
0         NaN
1    0.002029
2    0.007704
3   -0.003332
4    0.004573
BHP    pct_change
0         NaN
1    0.002877
2    0.010138
3   -0.011551
4   -0.001533
BLK    pct_change
0         NaN
1   -0.000607
2    0.009349
3    0.004145
4   -0.000184
BA    pct_change
0         NaN
1   -0.061498
2    0.004608
3   -0.010182
4    0.015242
BP    pct_change
0         NaN
1    0.003071
2    0.032266
3    0.002738
4   -0.001820
CAT    pct_change
0         NaN
1   -0.004733
2    0.007699
3    0.001423
4   -0.007630
CBRE    pct_change
0         NaN
1   -0.015424
2    0.010846
3   -0.004371
4    0.010577
CHGG    pct_change
0         NaN
1    0.002739
2    0.010678
3    0.013022
4   -0.003396
CHWY    pct_change
0         NaN
1   -0.036868
2    0.108605
3   -0.065846
4   -0.019198
KO    pct_change
0         NaN
1   -0.002815
2    0.003692
3   -0.011251
4   -0.008753
RACE    pct_change
0         NaN
1   -0.004359
2   -0.001075
3    0.008766
4    0.004497
F    pct_change
0         NaN
1   -0.004646
2   -0.004667
3   -0.014068
4    0.002378
GM    pct_change
0         NaN
1    0.000000
2    0.004661
3   -0.019845
4    0.001052
GS    pct_change
0         NaN
1    0.003368
2    0.003153
3    0.001115
4    0.004001
HAL    pct_change
0         NaN
1    0.007171
2    0.014596
3   -0.001053
4   -0.017562
IBM    pct_change
0         NaN
1    0.004139
2    0.002025
3    0.001660
4    0.004611
LAZ    pct_change
0         NaN
1    0.006069
2    0.002194
3   -0.013680
4    0.001664
LEVI    pct_change
0         NaN
1    0.318235
2   -0.012941
3   -0.015823
4    0.014240
MC    pct_change
0         NaN
1   -0.001364
2   -0.001821
3   -0.022344
4   -0.016325
MS    pct_change
0         NaN
1    0.004301
2    0.009041
3    0.006602
4    0.014992
JWN    pct_change
0         NaN
1    0.002256
2    0.000900
3   -0.000225
4   -0.016194
ORCL    pct_change
0         NaN
1    0.002659
2    0.004924
3   -0.000188
4   -0.002074
PCG    pct_change
0         NaN
1   -0.008256
2    0.012487
3    0.002569
4    0.007176
PFE    pct_change
0         NaN
1    0.005542
2    0.006710
3   -0.019519
4    0.014324
RL    pct_change
0         NaN
1   -0.004941
2   -0.009524
3   -0.001233
4   -0.006171
CRM    pct_change
0         NaN
1    0.003996
2    0.009666
3    0.005381
4    0.005228
SLB    pct_change
0         NaN
1    0.012120
2    0.013149
3   -0.001390
4   -0.016245
SHAK    pct_change
0         NaN
1    0.007220
2    0.001886
3    0.031256
4   -0.025927
SHW    pct_change
0         NaN
1   -0.012360
2    0.005938
3    0.008490
4    0.005154
SHOP    pct_change
0         NaN
1    0.010380
2    0.015015
3    0.013235
4   -0.010805
SNAP    pct_change
0         NaN
1   -0.008032
2    0.017206
3    0.122388
4   -0.010638
SPOT    pct_change
0         NaN
1   -0.007037
2   -0.012661
3   -0.022650
4    0.011908
BX    pct_change
0         NaN
1    0.004180
2    0.017544
3    0.006137
4    0.013070
TIF    pct_change
0         NaN
1   -0.004258
2    0.007093
3   -0.011186
4    0.011417
UBER    pct_change
0         NaN
1   -0.107529
2    0.077089
3    0.033283
4    0.041414
V    pct_change
0         NaN
1    0.007035
2    0.004877
3    0.011346
4    0.008171
WMT    pct_change
0         NaN
1   -0.001117
2    0.006709
3   -0.008179
4    0.002036
WM    pct_change
0         NaN
1    0.006610
2    0.005671
3    0.000791
4   -0.001878

In [24]:
nonacq_ticker_dfs = []

In [25]:
# Iterate through list of tickers to concat
# all pct_change CSVs to one main_df
for ticker in nonacq_ticker_list:
    
    try:
        # Bring in the previously created CSV files
        filepath = Path(f"nonacq_{ticker}_pct_change.csv")
        
        # Read the CSV
        ticker_data = pd.read_csv(filepath, index_col=0)
        
        # Create new DataFrame from CSV
        ticker_df = pd.DataFrame(ticker_data)
        
        # Create new DataFrame from CSV
        ticker_df[f"{ticker}"] = ticker_df["pct_change"]
        
        ticker_df = ticker_df.drop(columns="pct_change")
        
        # Add name of df to ticker_dfs list
        nonacq_ticker_dfs.append(ticker_df)
        
    except:
        print(f"Encountered error with {ticker}.")

In [26]:
nonacq_ticker_dfs

[          ACM
 0         NaN
 1   -0.002633
 2    0.002970
 3   -0.002303
 4    0.000000
 5    0.005937
 6   -0.007869
 7   -0.007931
 8    0.001999
 9   -0.023936
 10   0.003747
 11   0.001697
 12  -0.012534
 13   0.012350
 14   0.005422
 15   0.032693
 16  -0.004243
 17   0.001311
 18   0.014075
 19   0.008715
 20   0.006080
 21  -0.019084
 22   0.010052
 23   0.011878
 24   0.014911
 25   0.004689
 26   0.007156
 27   0.004016
 28   0.008923
 29   0.000610
 ..        ...
 146 -0.004600
 147 -0.013319
 148  0.008264
 149  0.006011
 150  0.009234
 151  0.062971
 152  0.015190
 153  0.011222
 154  0.013070
 155 -0.000487
 156 -0.000731
 157 -0.002194
 158 -0.002687
 159 -0.005878
 160 -0.005420
 161  0.004706
 162  0.008383
 163 -0.000244
 164 -0.021521
 165  0.021495
 166  0.018106
 167  0.014420
 168 -0.005212
 169  0.005716
 170  0.004973
 171  0.013195
 172  0.002558
 173 -0.020181
 174  0.030066
 175 -0.007355

 [176 rows x 1 columns],            AA
 0         NaN
 1    0.033430
 2    0.018987
 3   -0.037612
 4   -0.001793
 5    0.028736
 6   -0.000698
 7    0.005940
 8    0.021535
 9   -0.043863
 10  -0.003556
 11  -0.017131
 12   0.013435
 13   0.002866
 14   0.006074
 15   0.046165
 16  -0.031229
 17   0.005256
 18   0.020913
 19   0.008877
 20   0.003723
 21  -0.018881
 22   0.001718
 23  -0.022642
 24  -0.007020
 25  -0.019441
 26  -0.000721
 27   0.000000
 28  -0.038240
 29   0.055514
 ..        ...
 146 -0.010283
 147 -0.039481
 148 -0.004327
 149  0.015209
 150  0.031568
 151 -0.005705
 152  0.015128
 153 -0.015416
 154  0.059499
 155  0.061084
 156 -0.049675
 157  0.012702
 158  0.026532
 159 -0.025376
 160  0.013500
 161  0.023787
 162  0.003717
 163 -0.014352
 164 -0.023485
 165  0.051948
 166  0.047554
 167 -0.013968
 168 -0.030544
 169  0.030137
 170 -0.001330
 171 -0.013759
 172 -0.001800
 173 -0.043282
 174 -0.010839
 175 -0.004764

 [176 rows x 1 columns],          APLE
 0         NaN
 1    0.001218
 2    0.000000
 3    0.002433
 4   -0.001820
 5   -0.001824
 6   -0.003045
 7   -0.002443
 8    0.004287
 9   -0.017073
 10  -0.006824
 11   0.018738
 12   0.003679
 13   0.007330
 14  -0.011522
 15   0.015951
 16  -0.003019
 17   0.003634
 18   0.005432
 19   0.004202
 20  -0.000598
 21  -0.020335
 22   0.012210
 23  -0.002413
 24   0.001814
 25  -0.006035
 26   0.000000
 27  -0.007893
 28  -0.003060
 29  -0.010436
 ..        ...
 146  0.004326
 147 -0.011077
 148 -0.004356
 149  0.000000
 150  0.011875
 151 -0.009265
 152  0.003741
 153  0.002484
 154  0.004337
 155  0.004318
 156  0.013514
 157  0.006667
 158  0.003010
 159 -0.010804
 160 -0.004854
 161 -0.001220
 162 -0.000611
 163  0.002443
 164  0.004266
 165  0.003034
 166  0.006050
 167  0.003007
 168 -0.007194
 169 -0.009058
 170 -0.002438
 171  0.000000
 172 -0.014050
 173 -0.006196
 174  0.008105
 175 -0.005566

 [176 rows x 1 columns],           BCS
 0         NaN
 1    0.009490
 2    0.017626
 3    0.004619
 4    0.008046
 5    0.000000
 6    0.007982
 7   -0.027149
 8   -0.026744
 9   -0.023895
 10  -0.004896
 11  -0.001230
 12   0.013547
 13  -0.025516
 14  -0.002494
 15   0.038750
 16   0.009627
 17   0.023838
 18  -0.003492
 19  -0.012850
 20  -0.001183
 21  -0.007109
 22   0.007160
 23   0.009479
 24   0.017606
 25   0.008074
 26   0.001144
 27   0.012571
 28  -0.012415
 29  -0.005714
 ..        ...
 146 -0.007032
 147 -0.008499
 148  0.002857
 149  0.055556
 150  0.080972
 151 -0.014981
 152  0.058302
 153  0.000000
 154  0.003593
 155  0.011933
 156  0.004717
 157 -0.011737
 158  0.013064
 159 -0.007034
 160  0.025974
 161  0.002301
 162  0.003444
 163 -0.004577
 164 -0.008046
 165  0.004635
 166  0.003460
 167 -0.001149
 168 -0.009206
 169  0.004646
 170 -0.015029
 171  0.031690
 172  0.001138
 173 -0.010227
 174  0.002296
 175  0.005727

 [176 rows x 1 columns],         BRK.B
 0         NaN
 1    0.002029
 2    0.007704
 3   -0.003332
 4    0.004573
 5    0.011600
 6   -0.007403
 7   -0.009164
 8    0.005707
 9   -0.018980
 10  -0.005535
 11   0.005917
 12  -0.007028
 13   0.007279
 14   0.001146
 15   0.020459
 16  -0.005463
 17  -0.001030
 18   0.002111
 19   0.006026
 20  -0.000390
 21  -0.001608
 22  -0.001952
 23   0.010512
 24   0.018822
 25  -0.003894
 26   0.009822
 27  -0.006752
 28  -0.001806
 29  -0.002381
 ..        ...
 146 -0.004037
 147 -0.015200
 148  0.012739
 149  0.000822
 150  0.005898
 151 -0.000817
 152  0.007070
 153 -0.000430
 154 -0.003201
 155  0.000671
 156  0.013077
 157 -0.004114
 158  0.001614
 159 -0.003318
 160  0.007324
 161  0.005005
 162  0.000705
 163  0.001127
 164 -0.003142
 165  0.015288
 166  0.009962
 167  0.013304
 168  0.005071
 169  0.003333
 170 -0.006420
 171 -0.002079
 172  0.000181
 173 -0.005070
 174 -0.001866
 175  0.001732

 [176 rows x 1 columns],           BHP
 0         NaN
 1    0.002877
 2    0.010138
 3   -0.011551
 4   -0.001533
 5    0.017268
 6   -0.003395
 7    0.010409
 8    0.005619
 9   -0.026821
 10   0.008804
 11   0.014988
 12   0.006729
 13   0.002785
 14   0.012220
 15   0.024328
 16   0.001964
 17   0.003386
 18  -0.002131
 19   0.002670
 20   0.014202
 21  -0.010852
 22   0.008671
 23  -0.011404
 24   0.008518
 25  -0.014253
 26  -0.011603
 27  -0.004515
 28  -0.003084
 29   0.003276
 ..        ...
 146 -0.012601
 147 -0.006904
 148  0.001475
 149  0.017459
 150  0.025636
 151 -0.019956
 152  0.001234
 153 -0.010477
 154 -0.010380
 155 -0.002937
 156  0.017883
 157  0.003721
 158  0.009679
 159 -0.003263
 160  0.007162
 161  0.013612
 162 -0.003407
 163 -0.007039
 164 -0.009317
 165  0.022081
 166  0.018404
 167  0.018464
 168 -0.008679
 169  0.001362
 170 -0.013212
 171 -0.008269
 172 -0.000993
 173 -0.012122
 174  0.003822
 175  0.019840

 [176 rows x 1 columns],           BLK
 0         NaN
 1   -0.000607
 2    0.009349
 3    0.004145
 4   -0.000184
 5    0.015984
 6   -0.013417
 7   -0.010700
 8    0.001023
 9   -0.030207
 10  -0.004672
 11   0.017477
 12  -0.007169
 13   0.012701
 14   0.005647
 15   0.025786
 16  -0.004425
 17   0.006003
 18   0.006309
 19   0.007378
 20   0.002337
 21  -0.014188
 22   0.006707
 23   0.007566
 24   0.018471
 25  -0.005480
 26   0.032488
 27   0.002036
 28  -0.003850
 29  -0.003586
 ..        ...
 146 -0.009990
 147 -0.023655
 148  0.009706
 149  0.007695
 150  0.032399
 151  0.000484
 152  0.023583
 153  0.004387
 154  0.009565
 155 -0.012493
 156  0.019347
 157 -0.007340
 158  0.014967
 159 -0.005251
 160  0.011305
 161  0.014702
 162 -0.000857
 163  0.001673
 164 -0.011222
 165  0.016179
 166  0.015687
 167  0.012402
 168  0.014717
 169  0.001266
 170  0.000102
 171 -0.006977
 172  0.000000
 173 -0.002506
 174 -0.002018
 175  0.013145

 [176 rows x 1 columns],            BA
 0         NaN
 1   -0.061498
 2    0.004608
 3   -0.010182
 4    0.015242
 5   -0.017705
 6    0.003089
 7    0.007311
 8   -0.009198
 9   -0.028253
 10   0.022890
 11  -0.000216
 12   0.010341
 13   0.000615
 14   0.018641
 15   0.026532
 16  -0.002018
 17  -0.015381
 18   0.028903
 19  -0.009928
 20  -0.044421
 21  -0.014632
 22  -0.011110
 23   0.014304
 24   0.025611
 25  -0.011010
 26   0.016673
 27  -0.011003
 28   0.006755
 29  -0.012892
 ..        ...
 146  0.002236
 147 -0.006480
 148  0.002299
 149 -0.010561
 150  0.010566
 151 -0.004641
 152 -0.005949
 153  0.003963
 154 -0.009049
 155 -0.067902
 156 -0.037616
 157  0.017942
 158  0.010386
 159  0.011894
 160 -0.013699
 161  0.003090
 162  0.023615
 163 -0.008225
 164 -0.017771
 165  0.015534
 166  0.017092
 167  0.020508
 168 -0.011443
 169  0.008809
 170 -0.017660
 171  0.045470
 172 -0.011118
 173 -0.001047
 174  0.013628
 175  0.011539

 [176 rows x 1 columns],            BP
 0         NaN
 1    0.003071
 2    0.032266
 3    0.002738
 4   -0.001820
 5    0.008434
 6    0.005199
 7    0.001349
 8    0.000000
 9   -0.013025
 10  -0.009556
 11   0.006662
 12  -0.005249
 13   0.000918
 14   0.002063
 15   0.008463
 16   0.003175
 17   0.000000
 18  -0.001809
 19   0.008607
 20   0.015720
 21  -0.005306
 22   0.001111
 23  -0.003774
 24  -0.004457
 25   0.000000
 26  -0.004253
 27   0.003147
 28  -0.005155
 29   0.014643
 ..        ...
 146 -0.000271
 147 -0.002706
 148  0.008684
 149 -0.000269
 150  0.008073
 151 -0.001068
 152 -0.001603
 153 -0.004015
 154  0.014781
 155 -0.007415
 156  0.021078
 157  0.006271
 158  0.014282
 159  0.003840
 160  0.003571
 161 -0.002795
 162 -0.033384
 163  0.013973
 164 -0.014301
 165  0.020839
 166  0.017054
 167  0.011941
 168 -0.010796
 169 -0.002030
 170 -0.003306
 171 -0.001021
 172 -0.000511
 173  0.002044
 174 -0.005866
 175  0.005900

 [176 rows x 1 columns],           CAT
 0         NaN
 1   -0.004733
 2    0.007699
 3    0.001423
 4   -0.007630
 5    0.010779
 6    0.000373
 7   -0.008498
 8    0.007894
 9   -0.032001
 10   0.012407
 11   0.003501
 12  -0.004854
 13   0.008918
 14   0.023570
 15   0.035132
 16  -0.000428
 17  -0.006634
 18   0.006247
 19   0.001641
 20  -0.003847
 21  -0.024818
 22   0.008654
 23   0.009743
 24   0.016778
 25  -0.006728
 26   0.012692
 27   0.004999
 28   0.004344
 29  -0.006836
 ..        ...
 146 -0.006527
 147 -0.018960
 148  0.012461
 149  0.027210
 150  0.046540
 151 -0.000156
 152  0.020642
 153 -0.006411
 154  0.014440
 155 -0.010298
 156  0.011629
 157  0.011041
 158  0.012342
 159 -0.011009
 160  0.043930
 161  0.002362
 162  0.009068
 163 -0.007005
 164 -0.018099
 165  0.048549
 166  0.016818
 167 -0.003744
 168 -0.006012
 169  0.010447
 170  0.007823
 171 -0.001080
 172 -0.011216
 173 -0.012642
 174 -0.007267
 175  0.013037

 [176 rows x 1 columns],          CBRE
 0         NaN
 1   -0.015424
 2    0.010846
 3   -0.004371
 4    0.010577
 5    0.004937
 6   -0.006288
 7   -0.023729
 8    0.007089
 9   -0.029566
 10   0.000829
 11   0.010975
 12  -0.004506
 13   0.006790
 14   0.010627
 15   0.018200
 16   0.001986
 17   0.009713
 18  -0.000982
 19   0.008253
 20  -0.007796
 21  -0.010411
 22   0.009726
 23   0.007667
 24   0.017753
 25  -0.017826
 26  -0.011124
 27  -0.005131
 28   0.006348
 29  -0.004337
 ..        ...
 146 -0.004934
 147 -0.015668
 148  0.014306
 149  0.002980
 150  0.026342
 151  0.003088
 152  0.009811
 153 -0.000381
 154 -0.002287
 155 -0.002674
 156  0.008428
 157 -0.017854
 158  0.012763
 159  0.001528
 160  0.003051
 161  0.012165
 162  0.007136
 163  0.003356
 164 -0.004832
 165  0.023156
 166  0.000913
 167  0.012764
 168 -0.044292
 169  0.026752
 170  0.007156
 171  0.004919
 172 -0.001994
 173  0.000363
 174  0.009079
 175  0.015656

 [176 rows x 1 columns],          CHGG
 0         NaN
 1    0.002739
 2    0.010678
 3    0.013022
 4   -0.003396
 5    0.003164
 6    0.006793
 7   -0.013735
 8   -0.031029
 9   -0.073122
 10   0.014418
 11   0.027353
 12  -0.033151
 13   0.018898
 14   0.010069
 15  -0.009706
 16   0.014040
 17   0.015413
 18  -0.038333
 19  -0.009631
 20   0.006483
 21  -0.007515
 22   0.008112
 23   0.008852
 24  -0.007711
 25   0.024384
 26  -0.001046
 27  -0.014402
 28   0.004251
 29   0.008730
 ..        ...
 146  0.009511
 147 -0.008122
 148  0.022928
 149  0.008325
 150  0.020324
 151  0.015251
 152  0.013182
 153 -0.022693
 154  0.013932
 155 -0.011603
 156  0.011121
 157  0.000917
 158 -0.034799
 159  0.023403
 160  0.010816
 161 -0.003669
 162 -0.035901
 163 -0.004137
 164 -0.020134
 165  0.002935
 166 -0.046179
 167  0.143539
 168  0.026237
 169 -0.016560
 170  0.005908
 171  0.022320
 172  0.015226
 173  0.020091
 174  0.013037
 175  0.001369

 [176 rows x 1 columns],          CHWY
 0         NaN
 1   -0.036868
 2    0.108605
 3   -0.065846
 4   -0.019198
 5   -0.056968
 6   -0.023234
 7    0.008563
 8    0.017925
 9    0.029039
 10   0.050736
 11  -0.038571
 12  -0.019019
 13   0.024538
 14   0.013306
 15   0.003793
 16  -0.032267
 17  -0.002403
 18   0.005119
 19   0.017376
 20  -0.025618
 21  -0.008462
 22  -0.035050
 23   0.037587
 24  -0.065753
 25  -0.015640
 26  -0.019861
 27   0.104357
 28   0.032110
 29  -0.038519
 ..        ...
 79   0.033256
 80  -0.019087
 81  -0.031286
 82   0.000000
 83   0.025601
 84  -0.009985
 85   0.039178
 86  -0.011198
 87   0.009438
 88   0.011593
 89   0.029945
 90   0.007179
 91  -0.045260
 92  -0.002240
 93   0.039656
 94  -0.019431
 95  -0.054312
 96  -0.014746
 97  -0.028358
 98  -0.030807
 99  -0.006692
 100  0.032842
 101 -0.036282
 102 -0.028342
 103  0.000871
 104 -0.001740
 105  0.003486
 106  0.035606
 107 -0.018868
 108  0.000000

 [109 rows x 1 columns],            KO
 0         NaN
 1   -0.002815
 2    0.003692
 3   -0.011251
 4   -0.008753
 5    0.002428
 6    0.003303
 7   -0.000658
 8   -0.000439
 9    0.009229
 10   0.002177
 11   0.013252
 12  -0.000643
 13  -0.000644
 14   0.006011
 15  -0.002988
 16  -0.003211
 17  -0.008374
 18   0.006496
 19  -0.000215
 20   0.001722
 21   0.002578
 22  -0.000643
 23   0.001501
 24   0.000642
 25   0.005563
 26  -0.001064
 27   0.007029
 28   0.004230
 29  -0.001685
 ..        ...
 146 -0.012285
 147 -0.005383
 148  0.004666
 149 -0.003158
 150 -0.006709
 151  0.000000
 152  0.003940
 153 -0.000374
 154  0.005609
 155  0.018405
 156 -0.010040
 157 -0.007007
 158  0.014670
 159 -0.000549
 160 -0.015748
 161 -0.003349
 162 -0.002987
 163  0.009923
 164  0.009084
 165 -0.009737
 166 -0.014100
 167 -0.013549
 168  0.007249
 169 -0.009659
 170 -0.001530
 171 -0.007087
 172 -0.002508
 173  0.013537
 174  0.004198
 175  0.000760

 [176 rows x 1 columns],          RACE
 0         NaN
 1   -0.004359
 2   -0.001075
 3    0.008766
 4    0.004497
 5    0.003794
 6   -0.005065
 7    0.001064
 8    0.004858
 9   -0.028250
 10   0.019199
 11   0.014033
 12  -0.001354
 13   0.002033
 14   0.005637
 15   0.009342
 16   0.006812
 17   0.001544
 18   0.002130
 19   0.003444
 20   0.001387
 21  -0.005032
 22   0.000513
 23   0.005494
 24   0.009544
 25  -0.011114
 26   0.007736
 27  -0.002897
 28   0.016123
 29  -0.001858
 ..        ...
 146  0.001538
 147 -0.015021
 148  0.011929
 149  0.005693
 150  0.021112
 151  0.009457
 152  0.008593
 153  0.024151
 154 -0.014136
 155 -0.011167
 156  0.001283
 157 -0.013778
 158 -0.012541
 159  0.020136
 160  0.006837
 161  0.008713
 162  0.002096
 163  0.002282
 164  0.012521
 165  0.007869
 166  0.053352
 167 -0.025825
 168 -0.000966
 169 -0.002901
 170 -0.000364
 171 -0.003032
 172  0.003771
 173 -0.007029
 174  0.009825
 175  0.009246

 [176 rows x 1 columns],             F
 0         NaN
 1   -0.004646
 2   -0.004667
 3   -0.014068
 4    0.002378
 5    0.016607
 6    0.015169
 7   -0.021839
 8    0.021152
 9   -0.017261
 10  -0.003513
 11   0.029377
 12  -0.015982
 13   0.017401
 14   0.001140
 15   0.022779
 16   0.003341
 17   0.013319
 18   0.012048
 19   0.001082
 20   0.005405
 21  -0.009677
 22   0.013029
 23   0.006431
 24   0.006390
 25  -0.012698
 26   0.003215
 27   0.014957
 28   0.005263
 29  -0.005236
 ..        ...
 146 -0.006865
 147 -0.016129
 148  0.002342
 149  0.007009
 150  0.018561
 151  0.004556
 152  0.028345
 153  0.000000
 154  0.004410
 155  0.019759
 156 -0.027987
 157  0.004430
 158  0.015436
 159 -0.066232
 160  0.013953
 161 -0.012615
 162  0.003484
 163 -0.011574
 164  0.005855
 165  0.034924
 166  0.012373
 167  0.002222
 168 -0.011086
 169 -0.003363
 170  0.016873
 171  0.004425
 172 -0.004405
 173 -0.025442
 174 -0.002270
 175  0.018203

 [176 rows x 1 columns],            GM
 0         NaN
 1    0.000000
 2    0.004661
 3   -0.019845
 4    0.001052
 5   -0.002364
 6    0.007636
 7   -0.033185
 8    0.009459
 9   -0.024364
 10   0.008507
 11   0.003265
 12  -0.007052
 13   0.012292
 14   0.001079
 15   0.017790
 16   0.001324
 17   0.015340
 18   0.010419
 19   0.003867
 20   0.003082
 21  -0.005120
 22   0.010036
 23   0.002038
 24   0.009662
 25  -0.003526
 26   0.002274
 27   0.008321
 28   0.007752
 29  -0.019851
 ..        ...
 146 -0.004583
 147 -0.025036
 148  0.007674
 149  0.015231
 150  0.026255
 151 -0.001968
 152  0.021408
 153  0.010756
 154 -0.012551
 155 -0.000553
 156 -0.006635
 157  0.010576
 158  0.008262
 159 -0.021579
 160  0.025684
 161 -0.002722
 162  0.042849
 163 -0.007851
 164 -0.019784
 165  0.021798
 166  0.011061
 167 -0.004168
 168  0.004970
 169  0.001822
 170  0.004677
 171  0.001293
 172 -0.003357
 173 -0.036279
 174 -0.010487
 175  0.002446

 [176 rows x 1 columns],            GS
 0         NaN
 1    0.003368
 2    0.003153
 3    0.001115
 4    0.004001
 5    0.021235
 6   -0.006668
 7   -0.033811
 8    0.001338
 9   -0.028883
 10  -0.002381
 11   0.011564
 12  -0.003461
 13   0.006052
 14   0.004237
 15   0.024741
 16   0.003863
 17   0.017013
 18   0.006821
 19   0.000742
 20   0.000791
 21  -0.009480
 22   0.011764
 23  -0.000739
 24   0.024700
 25  -0.038154
 26   0.009654
 27   0.030024
 28  -0.009572
 29  -0.006362
 ..        ...
 146 -0.001992
 147 -0.015120
 148 -0.002635
 149  0.015342
 150  0.024066
 151  0.005570
 152  0.003110
 153  0.004650
 154 -0.004628
 155  0.000291
 156  0.013219
 157  0.001673
 158  0.008206
 159 -0.001278
 160  0.015068
 161  0.016431
 162 -0.000505
 163 -0.008408
 164 -0.011260
 165  0.018793
 166  0.011408
 167 -0.005594
 168 -0.001006
 169  0.022296
 170 -0.001702
 171 -0.017406
 172  0.006301
 173 -0.004945
 174  0.000502
 175  0.003737

 [176 rows x 1 columns],           HAL
 0         NaN
 1    0.007171
 2    0.014596
 3   -0.001053
 4   -0.017562
 5    0.032177
 6    0.013509
 7    0.028708
 8   -0.001993
 9   -0.043609
 10  -0.017055
 11   0.008144
 12   0.003161
 13   0.022059
 14   0.003768
 15   0.028669
 16  -0.006636
 17  -0.000334
 18   0.016372
 19   0.018080
 20   0.010333
 21  -0.015340
 22   0.007465
 23   0.005155
 24   0.004167
 25  -0.001277
 26   0.016619
 27  -0.006916
 28  -0.014562
 29  -0.001285
 ..        ...
 146 -0.010243
 147 -0.005991
 148  0.001096
 149  0.008758
 150  0.028215
 151 -0.010026
 152 -0.003198
 153 -0.021390
 154  0.011475
 155 -0.004322
 156  0.064026
 157  0.014788
 158  0.015578
 159 -0.014844
 160  0.028629
 161 -0.008789
 162  0.003941
 163 -0.046124
 164 -0.009774
 165  0.043636
 166  0.048780
 167 -0.000949
 168 -0.021378
 169  0.017476
 170  0.015267
 171 -0.001410
 172 -0.010353
 173 -0.019496
 174 -0.014064
 175  0.007378

 [176 rows x 1 columns],           IBM
 0         NaN
 1    0.004139
 2    0.002025
 3    0.001660
 4    0.004611
 5    0.005594
 6    0.001997
 7   -0.006335
 8    0.013181
 9   -0.014070
 10  -0.001936
 11   0.007472
 12  -0.006989
 13   0.004884
 14   0.008433
 15   0.015592
 16  -0.002094
 17   0.004406
 18  -0.005918
 19   0.003502
 20   0.000768
 21  -0.008927
 22   0.006403
 23   0.005314
 24   0.003964
 25  -0.003117
 26   0.008617
 27  -0.041546
 28   0.008770
 29  -0.010262
 ..        ...
 146 -0.011959
 147 -0.020527
 148  0.009322
 149  0.010453
 150  0.011550
 151 -0.005043
 152  0.006759
 153 -0.006224
 154 -0.055239
 155 -0.001266
 156 -0.011261
 157  0.010409
 158  0.003135
 159 -0.002307
 160  0.010219
 161  0.003913
 162 -0.015812
 163  0.010686
 164 -0.011238
 165  0.013460
 166  0.015790
 167  0.001598
 168  0.006454
 169 -0.007854
 170 -0.000581
 171 -0.015551
 172  0.000886
 173 -0.008186
 174 -0.003569
 175  0.002985

 [176 rows x 1 columns],           LAZ
 0         NaN
 1    0.006069
 2    0.002194
 3   -0.013680
 4    0.001664
 5    0.037109
 6    0.000801
 7   -0.017343
 8    0.013304
 9   -0.037781
 10   0.013088
 11  -0.005772
 12  -0.008018
 13   0.002230
 14   0.005006
 15   0.030991
 16   0.002952
 17   0.001606
 18   0.020572
 19  -0.004712
 20  -0.007102
 21  -0.017483
 22   0.013211
 23   0.006386
 24   0.021682
 25  -0.013458
 26   0.002361
 27  -0.004449
 28  -0.006835
 29  -0.021969
 ..        ...
 146  0.007519
 147  0.002583
 148  0.004581
 149  0.016244
 150  0.025519
 151 -0.004922
 152  0.037373
 153 -0.008742
 154 -0.010155
 155 -0.000810
 156  0.004323
 157 -0.006457
 158  0.013539
 159  0.000267
 160  0.002671
 161  0.026638
 162  0.005189
 163 -0.007744
 164 -0.028876
 165  0.001339
 166  0.017657
 167  0.019716
 168 -0.010570
 169  0.001042
 170  0.000781
 171  0.002601
 172 -0.002594
 173 -0.017945

In [32]:
main_nonacq_df = pd.concat(nonacq_ticker_dfs, axis=1)

main_nonacq_df = main_nonacq_df.transpose()

for index in main_nonacq_df.iterrows():
    
    main_nonacq_df["acquired"] = 0

main_nonacq_df.head()

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,acquired
ACM,NaN,-0.002633,0.002970,-0.002303,0.000000,0.005937,-0.007869,-0.007931,0.001999,-0.023936,...,0.014420,-0.005212,0.005716,0.004973,0.013195,0.002558,-0.020181,0.030066,-0.007355,0
AA,NaN,0.033430,0.018987,-0.037612,-0.001793,0.028736,-0.000698,0.005940,0.021535,-0.043863,...,-0.013968,-0.030544,0.030137,-0.001330,-0.013759,-0.001800,-0.043282,-0.010839,-0.004764,0
APLE,NaN,0.001218,0.000000,0.002433,-0.001820,-0.001824,-0.003045,-0.002443,0.004287,-0.017073,...,0.003007,-0.007194,-0.009058,-0.002438,0.000000,-0.014050,-0.006196,0.008105,-0.005566,0
BCS,NaN,0.009490,0.017626,0.004619,0.008046,0.000000,0.007982,-0.027149,-0.026744,-0.023895,...,-0.001149,-0.009206,0.004646,-0.015029,0.031690,0.001138,-0.010227,0.002296,0.005727,0
BRK.B,NaN,0.002029,0.007704,-0.003332,0.004573,0.011600,-0.007403,-0.009164,0.005707,-0.018980,...,0.013304,0.005071,0.003333,-0.006420,-0.002079,0.000181,-0.005070,-0.001866,0.001732,0

In [44]:
main_df = pd.concat([main_acq_df,main_nonacq_df], sort=True)

main_df.to_csv("main_df.csv")

main_df

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,acquired,174,175
RTN,NaN,0.002554,-0.005143,0.005991,-0.007012,0.000339,-0.010782,-0.034166,-0.033451,0.003665,...,0.009742,0.016232,0.018262,0.007075,0.012471,NaN,NaN,1,NaN,NaN
FOX,NaN,0.019388,0.026527,-0.003901,-0.032061,-0.049305,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
CELG,NaN,-0.009774,-0.044747,0.009529,-0.011714,-0.017261,0.017447,-0.026700,-0.017027,-0.003970,...,-0.028070,0.055565,0.004960,-0.006050,0.026590,0.039788,0.206933,1,NaN,NaN
AGN,NaN,0.016011,-0.011047,0.003388,-0.009972,0.000053,-0.046576,0.007713,-0.017139,-0.019187,...,0.042426,0.062334,0.020755,-0.000076,-0.009479,0.253608,NaN,1,NaN,NaN
DD,NaN,-0.005447,-0.000171,-0.008901,-0.008290,-0.003483,0.006641,0.007986,-0.004478,-0.006228,...,-0.003087,-0.003561,0.002953,0.002014,-0.006958,0.010589,0.026965,1,NaN,NaN
MDLZ,NaN,0.008600,0.010336,-0.004348,0.001798,-0.000256,-0.005899,0.006192,0.005128,-0.005612,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
ACM,NaN,-0.002633,0.002970,-0.002303,0.000000,0.005937,-0.007869,-0.007931,0.001999,-0.023936,...,0.014420,-0.005212,0.005716,0.004973,0.013195,0.002558,-0.020181,0,0.030066,-0.007355
AA,NaN,0.033430,0.018987,-0.037612,-0.001793,0.028736,-0.000698,0.005940,0.021535,-0.043863,...,-0.013968,-0.030544,0.030137,-0.001330,-0.013759,-0.001800,-0.043282,0,-0.010839,-0.004764
APLE,NaN,0.001218,0.000000,0.002433,-0.001820,-0.001824,-0.003045,-0.002443,0.004287,-0.017073,...,0.003007,-0.007194,-0.009058,-0.002438,0.000000,-0.014050,-0.006196,0,0.008105,-0.005566
BCS,NaN,0.009490,0.017626,0.004619,0.008046,0.000000,0.007982,-0.027149,-0.026744,-0.023895,...,-0.001149,-0.009206,0.004646,-0.015029,0.031690,0.001138,-0.010227,0,0.002296,0.005727
BRK.B,NaN,0.002029,0.007704,-0.003332,0.004573,0.011600,-0.007403,-0.009164,0.005707,-0.018980,...,0.013304,0.005071,0.003333,-0.006420,-0.002079,0.000181,-0.005070,0,-0.001866,0.001732
BHP,NaN,0.002877,0.010138,-0.011551,-0.001533,0.017268,-0.003395,0.010409,0.005619,-0.026821,...,0.018464,-0.008679,0.001362,-0.013212,-0.008269,-0.000993,-0.012122,0,0.003822,0.019840
BLK,NaN,-0.000607,0.009349,0.004145,-0.000184,0.015984,-0.013417,-0.010700,0.001023,-0.030207,...,0.012402,0.014717,0.001266,0.000102,-0.006977,0.000000,-0.002506,0,-0.002018,0.013145
BA,NaN,-0.061498,0.004608,-0.010182,0.015242,-0.017705,0.003089,0.007311,-0.009198,-0.028253,...,0.020508,-0.011443,0.008809,-0.017660,0.045470,-0.011118,-0.001047,0,0.013628,0.011539
BP,NaN,0.003071,0.032266,0.002738,-0.001820,0.008434,0.005199,0.001349,0.000000,-0.013025,...,0.011941,-0.010796,-0.002030,-0.003306,-0.001021,-0.000511,0.002044,0,-0.005866,0.005900
CAT,NaN,-0.004733,0.007699,0.001423,-0.007630,0.010779,0.000373,-0.008498,0.007894,-0.032001,...,-0.003744,-0.006012,0.010447,0.007823,-0.001080,-0.011216,-0.012642,0,-0.007267,0.013037
CBRE,NaN,-0.015424,0.010846,-0.004371,0.010577,0.004937,-0.006288,-0.023729,0.007089,-0.029566,...,0.012764,-0.044292,0.026752,0.007156,0.004919,-0.001994,0.000363,0,0.009079,0.015656
CHGG,NaN,0.002739,0.010678,0.013022,-0.003396,0.003164,0.006793,-0.013735,-0.031029,-0.073122,...,0.143539,0.026237,-0.016560,0.005908,0.022320,0.015226,0.020091,0,0.013037,0.001369
CHWY,NaN,-0.036868,0.108605,-0.065846,-0.019198,-0.056968,-0.023234,0.008563,0.017925,0.029039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
KO,NaN,-0.002815,0.003692,-0.011251,-0.008753,0.002428,0.003303,-0.000658,-0.000439,0.009229,...,-0.013549,0.007249,-0.009659,-0.001530,-0.007087,-0.002508,0.013537,0,0.004198,0.000760
RACE,NaN,-0.004359,-0.001075,0.008766,0.004497,0.003794,-0.005065,0.001064,0.004858,-0.028250,...,-0.025825,-0.000966,-0.002901,-0.000364,-0.003032,0.003771,-0.007029,0,0.009825,0.009246
F,NaN,-0.004646,-0.004667,-0.014068,0.002378,0.016607,0.015169,-0.021839,0.021152,-0.017261,...,0.002222,-0.011086,-0.003363,0.016873,0.004425,-0.004405,-0.025442,0,-0.002270,0.018203
GM,NaN,0.000000,0.004661,-0.019845,0.001052,-0.002364,0.007636,-0.033185,0.009459,-0.024364,...,-0.004168,0.004970,0.001822,0.004677,0.001293,-0.003357,-0.036279,0,-0.010487,0.002446
GS,NaN,0.003368,0.003153,0.001115,0.004001,0.021235,-0.006668,-0.033811,0.001338,-0.028883,...,-0.005594,-0.001006,0.022296,-0.001702,-0.017406,0.006301,-0.004945,0,0.000502,0.003737
HAL,NaN,0.007171,0.014596,-0.001053,-0.017562,0.032177,0.013509,0.028708,-0.001993,-0.043609,...,-0.000949,-0.021378,0.017476,0.015267,-0.001410,-0.010353,-0.019496,0,-0.014064,0.007378
IBM,NaN,0.004139,0.002025,0.001660,0.004611,0.005594,0.001997,-0.006335,0.013181,-0.014070,...,0.001598,0.006454,-0.007854,-0.000581,-0.015551,0.000886,-0.008186,0,-0.003569,0.002985
LAZ,NaN,0.006069,0.002194,-0.013680,0.001664,0.037109,0.000801,-0.017343,0.013304,-0.037781,...,0.019716,-0.010570,0.001042,0.000781,0.002601,-0.002594,-0.017945,0,0.000530,0.000529
LEVI,NaN,0.318235,-0.012941,-0.015823,0.014240,0.009964,0.017489,0.037902,-0.035669,0.012770,...,0.003540,0.009994,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
MC,NaN,-0.001364,-0.001821,-0.022344,-0.016325,0.018966,-0.004421,-0.020799,0.005967,-0.044603,...,0.016115,-0.026433,0.004859,0.000000,0.001422,0.000000,-0.034081,0,-0.014408,0.005967
MS,NaN,0.004301,0.009041,0.006602,0.014992,0.016155,-0.001817,-0.020933,0.002324,-0.032692,...,-0.001638,-0.003897,0.002059,0.010070,-0.001221,-0.001630,-0.012650,0,0.004546,0.007817
JWN,NaN,0.002256,0.000900,-0.000225,-0.016194,0.010288,0.008373,-0.024910,0.007135,-0.018967,...,-0.008424,0.006577,0.010890,-0.012928,0.021282,-0.014160,0.007588,0,0.017214,0.005817
ORCL,NaN,0.002659,0.004924,-0.000188,-0.002074,0.009822,0.010849,-0.025907,0.026596,-0.023501,...,0.003968,0.000539,0.005027,0.009110,-0.001062,0.002835,-0.006715,0,-0.002135,0.005883
PCG,NaN,-0.008256,0.012487,0.002569,0.007176,-0.011196,-0.018528,0.000524,-0.001572,0.019423,...,0.100413,-0.135000,-0.130058,0.076412,-0.033951,0.127796,-0.019830,0,-0.031792,0.107463
PFE,NaN,0.005542,0.006710,-0.019519,0.014324,0.000718,0.011720,-0.003073,0.004268,-0.011806,...,-0.014462,0.003469,-0.018612,0.003793,-0.003239,0.001083,-0.010008,0,-0.001366,0.019973
RL,NaN,-0.004941,-0.009524,-0.001233,-0.006171,0.028399,0.004831,-0.016505,0.015397,-0.035382,...,0.030493,-0.011562,0.146610,-0.016426,0.002110,-0.023244,-0.006286,0,0.006597,0.010953
CRM,NaN,0.003996,0.009666,0.005381,0.005228,0.002724,0.012226,-0.002562,0.021038,-0.032645,...,0.003490,0.004932,0.003586,0.010094,0.004159,0.006676,-0.001596,0,0.002768,0.000981
SLB,NaN,0.012120,0.013149,-0.001390,-0.016245,0.022883,-0.002537,0.024046,-0.001580,-0.039575,...,0.013245,-0.031590,0.014623,0.007206,0.001926,-0.005493,-0.032588,0,-0.009135,0.018727
SHAK,NaN,0.007220,0.001886,0.031256,-0.025927,0.028866,-0.014939,0.000555,0.020887,-0.015752,...,-0.206389,-0.026485,-0.031663,-0.014921,0.011763,0.008122,-0.023065,0,0.009541,0.003684
SHW,NaN,-0.012360,0.005938,0.008490,0.005154,0.000742,-0.002504,-0.002347,0.010180,-0.029772,...,-0.010665,0.018286,-0.010048,0.020879,-0.003337,0.013514,0.004257,0,0.006291,-0.001146
SHOP,NaN,0.010380,0.015015,0.013235,-0.010805,-0.001020,-0.017884,-0.003711,0.018178,-0.030488,...,-0.040304,-0.001624,-0.031422,0.041610,0.019083,0.007385,0.028636,0,-0.005918,-0.000224
SNAP,NaN,-0.008032,0.017206,0.122388,-0.010638,-0.019713,-0.028336,0.029163,0.006399,-0.025431,...,-0.033876,-0.028321,-0.017349,0.002119,0.014094,-0.000695,0.006259,0,-0.006911,-0.029923
SPOT,NaN,-0.007037,-0.012661,-0.022650,0.011908,-0.019238,0.017028,0.016602,0.000625,-0.034655,...,-0.024522,-0.012569,-0.002088,-0.002160,-0.008252,-0.001637,0.002664,0,0.013490,-0.008403
BX,NaN,0.004180,0.017544,0.006137,0.013070,0.016915,-0.011559,-0.006845,0.012349,-0.026383,...,-0.006960,-0.014207,-0.012298,0.002529,0.007374,0.000963,0.008853,0,0.004006,-0.002090
TIF,NaN,-0.004258,0.007093,-0.011186,0.011417,0.008181,-0.003390,0.000515,0.030803,0.031481,...,-0.026167,0.003138,0.002486,0.005360,-0.000796,-0.011308,-0.012807,0,0.003672,0.016828
UBER,NaN,-0.107529,0.077089,0.033283,0.041414,-0.025349,-0.007635,-0.002164,-0.006024,-0.018909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
V,NaN,0.007035,0.004877,0.011346,0.008171,-0.003216,-0.002388,-0.005434,0.013333,-0.017522,...,-0.014417,0.002268,0.009391,0.003026,0.003185,0.001114,-0.001836,0,0.001895,0.000111
WMT,NaN,-0.001117,0.006709,-0.008179,0.002036,0.012599,0.001906,-0.012118,0.004258,-0.007874,...,0.010972,0.005384,0.006109,-0.006571,-0.003349,0.000672,0.015615,0,-0.002728,-0.014753
WM,NaN,0.006610,0.005671,0.000791,-0.001878,0.004259,-0.001381,-0.004543,0.011409,-0.000490,...,-0.022649,0.014957,0.003821,0.006162,-0.005044,-0.004255,0.008545,0,0.010005,0.000982